# Generated by Django 6.0.7 on 2026-08-02 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GLS University Capstone Election', max_length=255)),
                ('start_timestamp', models.BigIntegerField(help_text='Unix timestamp for election start')),
                ('end_timestamp', models.BigIntegerField(help_text='Unix timestamp for election end')),
                ('merkle_root', models.CharField(blank=True, help_text='0x-prefixed 32-byte hash', max_length=66, null=True)),
                ('is_root_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('threat_score', models.FloatField(help_text='Anomaly confidence score from Scikit-Learn')),
                ('payload_size', models.IntegerField(help_text='Size of the rejected payload in bytes')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoterIdentity',
            fields=[
                ('voter_hash', models.CharField(max_length=66, primary_key=True, serialize=False, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Cleared by API Setu')),
                ('has_voted', models.BooleanField(default=False, help_text='Flipped to True when smart contract emits event')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.PositiveIntegerField(help_text='Matches the ID on the smart contract', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('party_symbol_url', models.URLField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.election')),
            ],
        ),
    ]
